name: ${project.name}
version: ${project.version}
description: Arena system for BattleCraft

main: mc.alk.arena.BattleArena

author: alkarin

softdepend: [BattleTracker, Essentials, Herochat, Heroes, IcePvPControl, Factions, GroupManager, MultiInv, Multiworld, Multiverse-Core, Multiverse-Inventories, PvPToggle, PvPTime, PvPTimer, SimpleClans, TagAPI, Towny, WorldEdit, WorldGuard, Vault]

commands:
    team:
        aliases: [arenateam]
        description: Team commands
        usage: /team <create|join|leave|decline> [arguments]
    arena:
        aliases: [a]
        description: Arena commands
        usage: /arena <create|alter|join|leave|top...> [arguments]
    skirmish:
        aliases: [sk]
        description: Skirmish commands
        usage: /arena <join|leave> [arguments]
    battleground:
        aliases: [bg]
        description: battleground commands
        usage: /arena <join|leave> [arguments]
    watch:
        description: watch a fight
        usage: /watch <arenaName | leave>
    tourney:
        description: Create a tournament
        usage: /tourney
    colosseum:
        aliases: [col]
        description: colosseum commands
        usage: /col
    freeforall:
        aliases: [ffa]
        description: join a ffa 
        usage: /ffa     
    deathMatch:
        aliases: [dm]
        description: join a dm 
        usage: /dm 
    arenaAlter:
        aliases: [arenaEdit,aa]
    battleArena:
        aliases: [ba]
        description: Admin commands
        usage: /ba
    battleArenaDebug:
        aliases: [bad]
        description: Debugging Commands
        usage: /bad
    battleArenaScheduler:
        aliases: [bas]
        description: Schedule Continuous Events
        usage: /bas


