configVersion: 2.0

## for more help configuring see the wiki
## https://github.com/alkarinv/BattleArena/wiki
## Change this file to customize your competition

<name>:
    enabled: true
    joinType: Queue
    database: <name> # or delete if you dont want wins/losses/top, needs BattleTracker
    rated: true # if database is enabled
    prefix: "&6[<name>]&e"
    command: <cmd>
    victoryCondition: LastManStanding
    nTeams: 2
    teamSize: 1+
    ### You can delete any stages/transitions that have no options
    ### for a list of options see wiki
    defaults: ## Global options for the entire match
        options: [woolTeams]
    preReqs: ## Prerequisites for joining
        options: []
    onEnter:
        options: [storeAll]
    onLeave:
        options: [restoreAll]
    onOpen:  ## opening the event
        options: [pvpOff]
    onJoin:  ## when they join the event
        options: [teleportIn]
    onPreStart: ## x seconds before onStart
        options: [pvpOff]
    onStart: ## Starting
        options: [pvpOn]
    onSpawn: ## what happens when a player spawns
        options: [hunger=20, health=20]
    onDeath: ## what happens when a player dies
        options: []
    onComplete: ## what happens when things end
        options: [teleportOut]
    winner: ## what to give the winner
        options: [health=20, hunger=20]
    losers: ## what to give the losers
        options: []
