Arena:
    enabled: true
    joinType: Queue
    database: arena
    rated: false
    prefix: "&6[Arena]&e"
    victoryCondition: LastManStanding
    nTeams: 2
    teamSize: 1
    preReqs:
        options: []
    onEnter:
        options: [storeAll]
    onLeave:
        options: [restoreAll]
    onStart:
        options: [teleportIn, blockBreakOff, woolTeams, pvpOn]
    onSpawn:
        options: [deEnchant, hunger=20, health=20]
        giveClass:
            default: gladiator
    onDeath:
        options: [clearInventory]
    onComplete:
        options: [teleportOut]
    winner:
        options: [health=20, hunger=20]
